### ISSUE TITLE
Broken in Node 4.x

### ISSUE THREAD

**Issue by martinheidegger** [nwhetsell/csound-api#1]
```
> csound-api@0.0.3 install /Users/martin/Private/projects/node-kissfft/node_modules/csound-api
> node-gyp rebuild

  CXX(target) Release/obj.target/csound-api/src/csound-api.o
../src/csound-api.cpp:1:10: fatal error: 'boost/lockfree/queue.hpp' file not found
#include <boost/lockfree/queue.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/csound-api/src/csound-api.o] Error 1
```

**Comment by nwhetsell** [comment]
It looks like either [Boost](http://www.boost.org) is missing, or `node-gyp` can’t find the Boost headers on your machine. If you’re on OS X, try installing Homebrew ([http://brew.sh](http://brew.sh)), and then install Boost by running `brew install boost` in a Terminal. If you already have Boost installed, you might have to patch the first line of src/csound-api.cpp (`#include <boost/lockfree/queue.hpp>`) to refer to where lockfree/queue.hpp is located on your machine.

**Comment by martinheidegger** [comment]
Oh - totally my oversight - sorry for disturbance.

**Comment by Nanotk303** [comment]
i have the same problem but don' t know how to patch the first line of   src/csound-api.cpp because i don't found it.I try to follow the explanation here: https://atom.io/packages/language-csound
for installing the necessary package, all is ok but i can't install csound-api  because this error of path... i'm not programer but want to use this atom stuff for my csound work.  thanks. S.

**Comment by nwhetsell** [comment]
Keep in mind that the `language-csound` Atom package doesn’t require `csound-api`. You only need `csound-api` if you want to change how that Atom package’s [list of opcode completions](https://github.com/nwhetsell/language-csound/tree/master/resources/opcode-completions.json) is generated, but changing how that list is generated requires [programming](https://github.com/nwhetsell/language-csound/blob/master/resources/update-opcode-completions.js). Assuming you’re installing Atom packages in the standard location, the list of opcode completions should already be in

```
~/.atom/packages/language-csound/resources/opcode-completions.json
```

If you really want to change how the list of opcode completions is generated, the issue with installing `csound-api` is most likely that [Boost](http://www.boost.org) isn’t installed on your computer. The easiest way to install Boost is probably through Homebrew. To install Homebrew, follow the instructions at [http://brew.sh](http://brew.sh). Then, to install Boost, run `brew install boost` in a Terminal. After that, try reinstalling `csound-api`.

Incidentally, csound-api.cpp should be in

```
~/.atom/packages/language-csound/node_modules/csound-api/src
```

**Comment by Nanotk303** [comment]
Thanks for your reply. boost is already instakked on my Computer. But i don't need to change how the list of opcodes is generated. i just want to use atom for Csound cud editing. but actually, when i launch atom and open a .csd file, i have an error message : Failed to load the language-csound package
Cannot find module 'first-mate'

don't know what is it. primarily, i supposed it was from my incapacity to install sound-api but, as i understand , it 's not that case. i don't know what to do for correct this issue.
S.

**Comment by nwhetsell** [comment]
No problem. Since this looks like an issue with `language-csound` and not `csound-api`, can you open a a new issue at https://github.com/nwhetsell/language-csound/issues? Mention which version of Atom you’re using (look in the Atom menu) and how you’re installing `language-csound` (I’m guessing you’re installing packages [the usual way from within Atom](http://flight-manual.atom.io/using-atom/sections/atom-packages/) but I want to make sure). In the meantime, I’ll try to reproduce this on my computer.

**Comment by Nanotk303** [comment]
Sorry, i have tried to install from command line. Now, i have uninstalled it and re-installed with the correct way for installing package and it works now.  thank you for your help and sorry for the disturb .
SB.
