### ISSUE TITLE
Error with `npm install csound-api`

### ISSUE THREAD

**Issue by jasonhallen** [nwhetsell/csound-api#20]
Hello,

I'm getting an error when trying `npm install csound-api`.  Here are some details:

* I'm on macOS 12.0.1 with the M1 chip.
* I already have Csound installed from the installers at csound.com.
* I installed Boost with `brew install boost`

The error I get looks like this:
```
npm ERR! code 1
npm ERR! path /Users/hallenj/Documents/csound/node/node_modules/csound-api
npm ERR! command failed
npm ERR! command sh -c /var/folders/lr/q0m4k0hx34q16lqv0x138d980000gn/T/install659759855.sh

...

../src/csound-api.cc:1:10: fatal error: 'boost/lockfree/queue.hpp' file not found
npm ERR! #include <boost/lockfree/queue.hpp>
```

When I run `g++ -E -x c++ - -v < /dev/null` to see the directories GCC searches I get this:
```
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
```
However, `/usr/local/include` is empty.  When I run `brew list boost` I see:

```
/opt/homebrew/Cellar/boost/1.79.0_1/include/boost/
/opt/homebrew/Cellar/boost/1.79.0_1/lib/libboost_atomic-mt.dylib
etc
```
I'm guessing there needs to be some connection between the GCC search paths and the Boost libraries.  Do you have any suggestions for what I might try next?  I'm super excited to work with your `csound-api`!

Thanks!
Jason

**Comment by nwhetsell** [comment]
I don’t have an M1 Mac on which I can reproduce this, but on Apple Silicon, [Homebrew installs](https://docs.brew.sh/Installation) into /opt/homebrew rather than /usr/local, so Clang needs to be told where to find Homebrew-installed headers and libraries.

Can you try running—

```sh
CPATH="$(brew --prefix)/include" \
LIBRARY_PATH="$(brew --prefix)/lib" \
npm install https://github.com/nwhetsell/csound-api.git
```

—and if that still results in an error about boost/lockfree/queue.hpp not being found—

```sh
export CPATH="$(brew --prefix)/include"
export LIBRARY_PATH="$(brew --prefix)/lib"
npm install https://github.com/nwhetsell/csound-api.git
```

I’m hoping that one or both of those will resolve the boost/lockfree/queue.hpp error, but I’m willing to bet you’ll end up with an error that csound/cwindow.h isn’t found. Csound’s installers put headers in a non-standard location, and the simplest way to resolve this is to reinstall Csound from Homebrew:

```sh
brew install csound
```

Rerunning one of the above `npm install` commands should then install csound-api.

**Comment by jasonhallen** [comment]
Thanks so much for the fast response, Nate!  `export CPATH="$(brew --prefix)/include"` and `export LIBRARY_PATH="$(brew --prefix)/lib"` did the trick with finding the Boost library.  You're also correct that I'm now getting an error due to the `cwindow.h` header.

I noticed that the Csound headers appear to be installed on my computer at `/Library/Frameworks/CsoundLib64.framework/Headers`.  Would I be able to use the same `export CPATH=` command to include this directory?  If that's a solution I'd prefer to do that over installing another Csound instance via Brew.  Otherwise, I can bite the bullet and do what you suggested.

Thanks!
Jason

**Comment by nwhetsell** [comment]
@jasonhallen You’re welcome, happy to help!

> Would I be able to use the same `export CPATH=` command to include this directory?

Yes, but that wouldn’t resolve the issue with Clang being able to find csound/cwindow.h. The problem is that on Linux and Windows, Csound puts headers in a folder named `csound`, so `#include <csound/cwindow.h>` works. However, Csound’s macOS installer puts headers in the folder you mention—`/Library/Frameworks/CsoundLib64.framework/Headers`—so `#include <csound/cwindow.h>` wouldn’t work even if that folder was added to `CPATH` (but `#include <cwindow.h>` would work).

The simplest fix for this—by far—is to install Csound using Homebrew. Csound from Homebrew has everything that the “official” installer includes, plus more (like the opcodes that were relegated to https://github.com/csound/plugins).

**Comment by jasonhallen** [comment]
Thanks for the explanation.  Now I get the problem.  I just installed Csound via Brew, and then I was able to install` csound-api` via npm.  Success!  Thanks!

Jason
