### ISSUE TITLE
Errors running csound-api and Electron

### ISSUE THREAD

**Issue by jasonhallen** [nwhetsell/csound-api#21]
Hi Nate,

I'm testing out running `csound-api` with Electron.  Here's the package.json file:

```json
{
  "name": "mell-fark",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "^20.0.1"
  },
  "dependencies": {
    "csound-api": "^0.10.20"
  }
}

```

`main.js` is your "Run Csound asynchronously, and stop Csound in mid-performance" example.  I've run `npm install` which successfully installs `csound-api` and Electron.

First of all, when I run `node main.js` everything works well.  However, when I try to run `main.js` through Electron with
```
npm start
```
I get this error message:

```
Error: The module '/Users/hallenj/Documents/csound/node/node_modules/csound-api/build/Release/csound-api.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 107. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hallenj/Documents/csound/node/main.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
```

I've tried running `npm rebuild` and `npm install` and following suggestions in StackExchange for similar error messages, but nothing is fixing this.  Do you have any suggestions or at least an explanation of what is going on?

Thanks for any help you can give,
Jason

**Comment by jasonhallen** [comment]
I saw this issue with a similar error: https://github.com/nwhetsell/csound-api/issues/6.

It sounds like I might need to change my Node version to work better with whatever version Electron comes bundled with.  However, I don't see a NODE_MODULE_VERSION 107 in the official list of Node versions.  Perhaps I could also install a different version of Electron, but I'm not sure which one.  I can't quite figure it out from the error codes.

Thanks,
Jason

**Comment by nwhetsell** [comment]
This isn’t actually an issue with csound-api, but to try and get you up and running, [Electron’s documentation](https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules) says you need to rebuild Node.js addons using [`electron-rebuild`](https://github.com/electron/electron-rebuild). You can do this by installing `electron-rebuild`—

```sh
npm install --save-dev electron-rebuild
```

—and then running it. However, if you do this, rebuilding csound-api will fail due to another problem. [Electron v20](https://www.electronjs.org/releases/stable?version=20#20.0.0) uses [V8](https://v8.dev) v10.4, but the latest Node.js (currently v18.7.0) is [still on V8 v10.2](https://nodejs.org/en/download/releases/). It looks like there’s a V8 function that’s deprecated in v10.2, but removed from v10.4, and this causes rebuilding csound-api against Electron v20 to fail:

```
⠧ Building module: csound-api, Completed: 0  CXX(target) Release/obj.target/csound-api/src/csound-api.o
⠇ Building module: csound-api, Completed: 0In file included from ../src/csound-api.cc:4:
In file included from ../../nan/nan.h:180:
../../nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
typedef v8::Local<v8::AccessorSignature> Sig;
                  ~~~~^
⠏ Building module: csound-api, Completed: 0In file included from ../src/csound-api.cc:4:
../../nan/nan.h:2546:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/nathanwhetsell/.electron-gyp/20.0.1/include/node/v8-template.h:814:8: note: candidate function not viable: no known conversion from 'imp::Sig' (aka 'int') to 'v8::SideEffectType' for 7th argument
  void SetAccessor(
       ^
/Users/nathanwhetsell/.electron-gyp/20.0.1/include/node/v8-template.h:807:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::AccessorGetterCallback' (aka 'void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') for 2nd argument
  void SetAccessor(
       ^
⠋ Building module: csound-api, Completed: 02 errors generated.
⠙ Building module: csound-api, Completed: 0make: *** [Release/obj.target/csound-api/src/csound-api.o] Error 1
✖ Rebuild Failed
```

Until [NAN](https://github.com/nodejs/nan) is updated to fix this, you’ll need to use Electron v19:

```sh
npm install --save-dev electron@19
```

You should then be able to rebuild csound-api (possibly after doing the `export CPATH`/`LIBRARY_PATH` dance from issue #20):

```sh
./node_modules/.bin/electron-rebuild
```

After I do all that, running

```
npm start
```

runs Csound as expected (turn your volume down). You can quit Electron by pressing <kbd>Control</kbd>-<kbd>C</kbd>.

**Comment by jasonhallen** [comment]
Thank you so much, Nate!  This worked like a charm.  I was able to get Electron and csound-api to play well together!

Jason
