### ISSUE TITLE
Add CompileOrc and EvalCode to CsoundEventType

### ISSUE THREAD

**Issue by hlolli** [nwhetsell/csound-api#8]
Feature request for adding CompileOrc and EvalCode to csoundEventType, like was done with readScore and inputMessage. This would prevent csound from waiting when those events are fired, enabling realtime instrument changes, these delays become more extreme with higher ksmps value. Like before, this is only a problem on linux. 

The following example on linux is very modest, compared to the delay I experience on my live-coding environment.

```javascript
const csound = require('bindings')('csound-api.node');
const Csound = csound.Create();
csound.SetOption(Csound, '--output=dac');
csound.CompileOrc(Csound, `
  0dbfs = 1
  //ksmps = 128
  ksmps = 1
  alwayson 1
  instr 1
    asig poscil 80, 0.2
    asig2 poscil 162, 0.2
    aenv expon 1, 0.1, 0.0001
    outc (asig2+asig)*aenv
  endin
`);
var cnt = 0;
setInterval(function() {csound.InputMessage(Csound, `i 1 0 1`);
			cnt += 1;
			if ((cnt % 10) == 0 ) {csound.CompileOrc(Csound,
								 `instr 1
    asig poscil ${Math.random()*60+60}, 0.2
    asig2 poscil ${Math.random()*120+60}, 0.2
    aenv expon 1, 0.1, 0.0001
    outc (asig2+asig)*aenv
  endin`
							 )};},100);
if (csound.Start(Csound) === csound.SUCCESS) {
  csound.PerformAsync(Csound, () => csound.Destroy(Csound));
  setTimeout(() => csound.Stop(Csound), 20000);
}
```

**Comment by hlolli** [comment]
this was easily implemented, did .compileOrc https://github.com/hlolli/csound-api and it works. Now I'm performace ready on my linux. I could make a pull request and add .EvelCode, if you want to. Im not a c++ expert and maybe best to leave the code to you, you tell.

**Comment by nwhetsell** [comment]
I added `CompileOrc` in commit 5d1cf0ac6b926e668145a77eb024bbb191f75c67, but not `EvalCode`. The problem is that some Csound API functions (including `csoundCompileOrc` and `csoundEvalCode`) return something. For compatibility with the Csound API, the [`CsoundSynchronousEventHandler`](https://github.com/nwhetsell/csound-api/blob/5d1cf0ac6b926e668145a77eb024bbb191f75c67/src/csound-api.cc#L195) implementations of event handling functions all return whatever the Csound API functions return, and currently these are just [status codes](https://github.com/nwhetsell/csound-api#status-codes). The [`CsoundAsynchronousEventHandler`](https://github.com/nwhetsell/csound-api/blob/5d1cf0ac6b926e668145a77eb024bbb191f75c67/src/csound-api.cc#L504) implementations return, for better or worse, `CSOUND_SUCCESS`. This means that if you call [`PerformAsync`](https://github.com/nwhetsell/csound-api#PerformAsync), and then call [`ReadScore`](https://github.com/nwhetsell/csound-api#ReadScore) with a garbage score, `ReadScore` will immediately return a value indicating that the score was read successfully, even though reading the score will certainly fail later when `csoundReadScore` is actually called.

The problem with `EvalCode`, of course, is that its return value isn’t a status code at all. When you call `EvalCode`, you expect Csound to compute a number for you, and that number should be returned by `EvalCode`. But if `csoundEvalCode` (the C function) is called after `EvalCode` (the JavaScript function) returns, there isn’t really a sensible value for `EvalCode` to return; Csound hasn’t evaluated any code yet.

I’m not sure of the best way to address this, even in principle (although [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) would likely make an appearance). No matter what, it’s likely that a completely different JavaScript API for Csound would be needed to handle this.

**Comment by hlolli** [comment]
Good point, I never realized so far what the difference is between csoundEvalCode and csoundCompileOrc, they do exacly the same thing, but EvalCode apparently returns status codes, which I don't really see as very helpful, as parse errors would be reported in the stderror by Csound (so I get all I need from CompileOrc). Actally not a good name for these functions, one could really go Supercollider style live-coding with nothing but csoundCompileOrc, but a newcommer would probably grab for csoundEvalCode for such activities. But EvalCode may not be the only performance function that we may want to make async. for example channels(which I haven't testet tbh), I can foresee that there could be some cases where Promise would be handy, that adds probably lot of complexity. In the case of getting return value, wouldn't it make sense to run the function and allow the data come from Csound into node whenever. So an evaluation may fail but the user won't know until a second or two later.

Good for now, more cocktails on me,
cheers!
